version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install @semantic-release/changelog @semantic-release/git
      - run: npx semantic-release
